name: CI/CD Pipeline Frontend App

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: echo "Start to deploy Staging"
      
      - name: Checkout Staging branch
        uses: actions/checkout@v4
      
      - name: Install pnpm
        run: npm install -g pnpm@latest
         
      - name: Install Depedencies
        run: pnpm install
        
      - name: Check Code Linter
        run: pnpm lint
      
      - name: Build Docker Image
        run: docker build -t uudilz/digicommerce-fe .
      
      - name: Login to Docker HUB
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Push Docker Image to HUB
        run: docker push uudilz/digicommerce-fe
      
      - name: Setup SSH to Server
        run: 
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.FRONTEND_SERVER_IP }} >> ~/.ssh/known_hosts
        
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

